export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const GET_STOCKS = 'GET_STOCKS';
export const GET_COMPANY_INFO = 'GET_COMPANY_INFO';
export const RETURN_TO_STOCKS_PAGE = 'RETURN_TO_STOCKS_PAGE';
